### ISSUE TITLE
Comparing complex types

### ISSUE THREAD

**Issue by saelo** [mj3-16/mjtest#22]
The testcase [comparison_operators.mj](https://github.com/mj3-16/mjtest/blob/master/tests/semantic/comparison_operators.mj) has the following expression: `new A() == new boolean[1];`. Should this be valid? The way we currently implement the type check for equality expressions is that complex types can only be compared if they are either equal (including classname and/or array dimensions) or if at least one of the operands is `null`.

**Comment by sgraf812** [comment]
We talked about this at the last meeting and came to the conclusion that we should be able to compare arbitrary references in compliance with the Java spec.

**Comment by sgraf812** [comment]
Fixed by #23.
