### ISSUE TITLE
Main as identifier

### ISSUE THREAD

**Issue by CodeMonkey90** [mj3-16/mjtest#32]
I'd argue that main_as_identifier.invalid.mj is incorrect. Yes, minijava does not support overloading, but main is not a regular method anyway, so it wouldn't participate in overload resolution anyhow.

Therefore, I see no reason to disallow an instance method main(...) in the same class as the static main method.

**Comment by parttimenerd** [comment]
This cases was once valid, it became invalid after a discussion in my group. It's debatable whether or not the `main` method is really special (you can define a method with name `main` in another class without any problems). We should probably discuss it in the meeting today.

**Comment by sgraf812** [comment]
So, would you allow the following code?

```
class A {
  public static void main(String[] args) { }
  public void main(String[] args) { }
}
```

If yes, you're disagreeing with Java (and thus the spec). If not, how do you justify that? The only valid argument is 'has the same signature as main'. Now, we may not do overload resolution (so signatures may not be taken into account), so the argument can only be 'has the same name as main'. q.e.d

**Comment by CodeMonkey90** [comment]
So this bug was closed as won't fix despite there being multiple possible interpretations? I'm confused.

**Comment by parttimenerd** [comment]
No. It was closed because our advisor told us that the test case is correctly identified as invalid.
There are of course several possible interpretation but our advisor decided which one is correct in the context of compiler lab.
