### ISSUE TITLE
New test tests behavior outside specification

### ISSUE THREAD

**Issue by CodeMonkey90** [mj3-16/mjtest#52]
Today, a new test `use_variable_after_declaration_in_same_statement_without_init.invalid.mj` was added:

```java
class Foobar {
  public static void main (String[] args) {
      int x = x + 1;
  }
}
```

`javac` rejects the program with the following error message, which states that the "definite assignment" rule was violated:

> error: variable x might not have been initialized

However, the specification states:

> Die „Definite Assignment“-Regeln von Java müssen nicht beachtet werden.

gcc, as an example for a compiler which does not check that a variable was initialized before use, accepts statements such as `int x = x + 1;`.

Therefore, the test checks behavior that we were specifically allowed not to implement. This means that the test is incorrect and should be removed. The behavior in such cases should be implementation-defined.

**Comment by sgraf812** [comment]
Thank god. I should've read the spec more carefully.
