### ISSUE TITLE
Extending language without checking with other teams first is bad for universe

### ISSUE THREAD

**Issue by suluke** [mj3-16/mjtest#55]
This is a serious issue, since it has a direct impact on the harmony of the universe. Please be nice and fix this immediately, or I will fail to get my healthy dose of sleep tonight, resulting in a grumpy and thereful harmful @suluke

Examples where this occurs is:
https://github.com/mj3-16/mjtest/blob/bc2c92d5c925a23bd36e267d605d848cfb5425a7/tests/exec/lcg_test.java

A counterexample where harmony can be found is here: https://github.com/mj3-16/mjtest/pull/37 and here https://github.com/mj3-16/mjtest/pull/39 

I propose creating a feature branch for tests using your custom extensions. Bob Ross, master of all harmony, likes branches (especially in on trees)

**Comment by sgraf812** [comment]
I'm not actually sure how the preprocessor works, but those tests run just fine for us (and we didn't implement import statements ofc). I'll try to find out where the preprocessed results can be found.

If that test errors for you, mjtest should normally print out the source file it tried to compile (modulo line numbers). Try to work with that.

**Comment by sgraf812** [comment]
Look into `tests/exec/.preprocessed/lgc_test.java` for the actual code passed to the compiler.

**Comment by suluke** [comment]
Thanks for the fast reply.

**Comment by parttimenerd** [comment]
The preprocessor implements something akin to Cs preprocessor (i.e. just simple text processing).
You can use the `preproc` from the commandline (see https://github.com/mj3-16/mjtest/tree/master/preproc for a detailed description).
`preproc` is a way to add useful features without extending the language compiled by the compilers.
You can probably just run all files in the `exec` branch through the preprocessor (it doesn't alter valid MiniJava files).
Please consider writing issues or pull request for missing features or bugs in `preproc`.
