### ISSUE TITLE
Python 3.4 stated, actually 3.5 needed

### ISSUE THREAD

**Issue by FlorianLoch** [mj3-16/mjtest#57]
The README.md states that one needs at least Python 3.4 - running on 3.4.2 failed (default py version on Ubuntu 14.04, with 16.04 it's fine as > 3.5 is the default version here). There is an `import` for `typings` which seems to be introduced first with Python 3.5.

**Comment by parttimenerd** [comment]
You're correct, Have you tried to install the `typing` package manually via `pip3`?

**Comment by FlorianLoch** [comment]
Nope, I simply upgraded my Docker image to 16.04 and therefore to Python
3.5.2. Just opened this issue for the docs, 14.04 was a bit old anyway ;)
