### ISSUE TITLE
Make preprocessor optional

### ISSUE THREAD

**Issue by tcm-marcel** [mj3-16/mjtest#58]
I have trouble using the preprocessor on my computer (Ubuntu 16.04, works on my Laptop but not on my workstation, still haven't figured out why) and therefore can not use the whole Test Suite. 
Please make the preprocessor optional, because it is not an essential part of the Test Suite.

**Comment by parttimenerd** [comment]
Is the problem the new preprocessor? Does the old one (for import statements) work for you?

**Comment by parttimenerd** [comment]
I've removed the new preprocessor from the main mjtest version.

**Comment by tcm-marcel** [comment]
The old preprocessor works for me. Thank you!
