### ISSUE TITLE
Readme says `exec` instead of `compile`

### ISSUE THREAD

**Issue by suluke** [mj3-16/mjtest#66]
I hope I didn't overlook anything. I wanted to run the executable tests on our backend and was confused when 
`$ ./mjt.py exec ../minijavac/run`
gave met this output:
```
----------------------------------------
All 0 run tests succeeded
```

After fiddling around a bit more, I came to the conclusion that it should be `compile` instead of `exec`. This means, lines 150 and 155 in the readme are currently wrong. It also wouldn't be bad to tell the user that `exec` is somehow not maintained/unsupported.

**Comment by parttimenerd** [comment]
You're correct, I forgot adding the new mode to the README.
