### ISSUE TITLE
.invalid exec tests probably undefined behavior

### ISSUE THREAD

**Issue by suluke** [mj3-16/mjtest#69]
I just found out about the `div_and_mod.invalid.java` test case and was curious what the java specification said should be returned by the application (JRE) if an exception bubbles up to `main` and isn't caught. The first thing I found was [this stackoverflow article](https://softwareengineering.stackexchange.com/questions/20573/why-does-java-exit-with-success-after-an-uncaught-exception), which argues that the exact behavior is not defined in this case. I also had a brief look into the Java Language Specification (8th edition) and there I was also unable to find any evidence that the currently enforced behavior (return value != 0 I think) is indeed the expected behavior. I think the relevant section here is 11.3.

I can confirm though that openjdk 1.8 does return 1 as exit status in this case. Since I am currently a bit clueless about how to implement this in our x86 backend, my first instinct was to open this issue and to loudly shout "UNDEFINED BEHAVIOR! UNDEFINED BEHAVIOR!". Finally, I had a look into the "Sprachbericht" where it says in chapter 4, semantics:
> Ausnahmen treten nicht auf. Das Verhalten in Situationen wie dem Zugriff auf
> null-Referenzen oder Division durch 0 ist undefiniert.

I hope I didn't overlook something that legitimizes the current behavior of the test runner.
Cheers!

**Comment by sgraf812** [comment]
You're right wrt. to undefined behavior, but the tests aren't really testing what exactly you are doing when there is a division by zero (at least they should not), as long as you crash! I certainly would not want that program to print 0 and exit successfully.

**Comment by suluke** [comment]
I don't think you are correct here. The Sprachbericht explicitly states there *ARE NO* runtime errors. Aside from that, using the the return value to detect an error cannot even be regarded as a reliable technique in the real-java world, as can be seen from the linked SO post. So I see 2 options here:
1. Please remove the test from the suite OR
2. You could start arguing about how easy this is to implement in 3 extra lines of code or less so I will accept the test and quickly fix my compiler to conform

But simply stating your own opinion 
> I certainly would not want that program to print 0 and exit successfully

will not suffice as an argument here, I'm afraid :smile:

**Comment by sgraf812** [comment]
Well, this basically tests your IR generation if it adds the necessary `getCurrentMem`/`setCurrentMem` calls while handling div and mod. So it should be enough to `setCurrentMem` on the `Proj M` on the result tuple of div and mod.

But we could also just take this test out again. It's subtle what it means to get this wrong, though:

```
int i = 0;
while (i > 0) {
  System.out.println(5/i);
}
```

If you would move the loop invariant expression out of the while loop in a naive way, this will definitely not be a valid optimization anymore. This can't happen if you pass this test (or at least is much less likely).

**Comment by suluke** [comment]
Ok, I see why one would want to have this case. But I don't agree with the way the test is currently implemented for the reasons stated above. Would it be possible to rewrite this test in way where a wrong implementation would produce a different result, without relying on runtime errors?
Wouldn't the same check be achieved if you printed ANY value inside the loop?

**Comment by sgraf812** [comment]
Of course. I haven't given it enough thought before and thought this was convered by the semantics.
The above should do (maybe make it less obvious for the compiler that `i` is 0): It should never throw an error. If it did, you know you screwed up an optimization.

**Comment by suluke** [comment]
I don't think you need runtime errors to show the problem you're after. If your optimization were to incorrectly make dead code living again, you could replace it with a print, no? Errors are just another type of side effects that should not be converted from dead to living by any optimization.
My opinion is still that it would be better to remove the test case.

**Comment by sgraf812** [comment]
OK, I'll try again.

```
int i = 0;
while (i > 0) {
  System.out.println(5/i);
}
```

This is a perfectly fine program without undefined behavior. It does nothing, it is equivalent to a program that exits immediately. 

Now, an optimizer might come to the conclusion that  `5/i` is loop invariant code, so with a very naive invariant code motion optimization (which wouldn't actually be an optimization, more of a heuristic), we get the following code:

```
int i = 0;
int tmp = 5/i;
while (i > 0) {
  System.out.println(tmp);
}
```

Which exhibits undefined behavior. Boom, we broke our promise that the compiler preserved semantics.

Now arguably, an actual invariant code motion optimization would avoid this kind of transformation by duplicating the loop header and inserting an intermediate block where the expression is computed. But, let's face it: We don't have time to get such elaborate optimizations right :D

**Comment by suluke** [comment]
Ok, I didn't consider the possibility that someone would move the division alone out of the loop. Unfortunately, I don't have a solution for you for this problem, i.e. creating a test that catches this kind of bugs without defining behavior for undefined-behavior situations.

**Comment by sgraf812** [comment]
Well, it's easy: That one is a valid test case. There's no way this program behaves undefined and an optimization (or IR code generator) that does this is invalid.

**Comment by suluke** [comment]
Ok, I get it now. This seems indeed like the best option possible given that errors are undefined. You can have your explicit error return code and we don't have to do anything in our compiler, although the test case is entirely meaningless for us as long as we don't also implement error detection with return codes.
