### ISSUE TITLE
Please take down your forks of mjtest

### ISSUE THREAD

**Issue by sgraf812** [mj3-16/mjtest#78]
Hey folks! It has been two years since our compiler lab, so the next round will begin shortly. I urge you to take down your forks of `mjtest`, so that the new teams can make the same errors we have made all over again :)

**Comment by sgraf812** [comment]
Pinging @Azegor @chanakam2000 @mini-java @minijavacc @moben @pserrer @SrTobi-Forks (@SrTobi)

**Comment by chanakam2000** [comment]
done

**Comment by pserrer** [comment]
Done

**Comment by minijavacc** [comment]
done

**Comment by moben** [comment]
done

**Comment by sgraf812** [comment]
Ping @Azegor, team @mini-java (@tharina, @bgoerzig, @FlorianLoch,@saelo)

**Comment by sgraf812** [comment]
Ping @Azegor, team @mini-java (@tharina, @bgoerzig, @FlorianLoch, @saelo)

Not trying to be annoying, but it would be really great if this round's teams don't find our test cases and get creative on their own.

**Comment by sgraf812** [comment]
Thanks, all!
